/* yoga.js — 48 posturas de yoga que se suman al catálogo de ejercicios.

   El catálogo principal (free-exercise-db) no tiene yoga: ni la categoría ni
   una sola postura. Los datos vienen de Yoga API (github.com/alexcumplido/
   yoga-api, MIT) y se guardan aquí copiados en vez de llamar a su servidor:
   está en un plan gratuito que se duerme, y la app tiene que abrir sin
   conexión.

   El nombre en español, el nivel y los músculos son cosa mía: los datos
   originales no los traen, y sin músculos las posturas no saldrían en ningún
   filtro de la app ni servirían para armar una rutina.

   Licencia de las ilustraciones, según la fuente: las rojas son CC0 y las
   rosas y verdes son de Flaticon, de uso comercial permitido citando al
   autor. La cita está en la pantalla de Ejercicios. */
(function (g) {
  'use strict';

  const POSTURAS = [
    { id: "yoga_boat", name: "Boat", nameEs: "Postura del barco", sanskrit: "Navasana",
      level: "intermediate", primary: "abdominals", secondary: ["quadriceps", "lower back"],
      img: "https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483071/yoga-api/1_txmirf.png",
      desc: "From a seated position the feet are lifted up so that the thighs are angled about 45-50 degrees relative to the earth.  The tailbone is lengthened into the earth and the pubis pulls toward the navel.  The shoulder blades are spread across the back and the hands reach around the back of the calves, with legs pulled towards the body.  The chin is tipped slightly toward the sternum so that the base of the skull lifts lightly away from the back of the neck.  Gaze is forward.",
      bien: "Strengthens the abdomen, hip flexors, and spine.  Stimulates the kidneys, thyroid and prostate glands, and intestines.  Helps relieve stress.  Improves digestion." },
    { id: "yoga_bow", name: "Bow", nameEs: "Postura del arco", sanskrit: "Dhanurasana",
      level: "intermediate", primary: "chest", secondary: ["abdominals", "quadriceps", "shoulders"],
      img: "https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483072/yoga-api/3_aa0fgk.png",
      desc: "From a prone position with the abdomen on the earth, the hands grip the ankles (but not the tops of the feet) with knees no wider than the width of your hips.  The heels are lifted away from the buttocks and at the same time the thighs are lifted away from the earth working opposing forces as the heart center, hips and back open.  The gaze is forward.",
      bien: "Stretches the entire front of the body, ankles, thighs and groins, abdomen and chest, and throat, and deep hip flexors (psoas).  Strengthens the back muscles.  Improves posture.  Stimulates the organs of the abdomen and neck." },
    { id: "yoga_bridge", name: "Bridge", nameEs: "Postura del puente", sanskrit: "Setu Bandha Sarvangasana",
      level: "beginner", primary: "glutes", secondary: ["hamstrings", "lower back", "chest"],
      img: "https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483074/yoga-api/4_qq6nxw.png",
      desc: "From a supine position, on your back, the hips are pressed up with the heels of the feet rooted into the earth close to the sits bones.  The toes are actively lifted and the pelvis tucked.  The thighs are parallel to the earth and the fingers are interlaced under the body with the ribcage lifted and the heart open.  The back of the neck rests on the earth.  The gaze is to the sky.",
      bien: "Stretches the chest, neck, and spine.  Stimulates abdominal organs, lungs, and thyroids.  Rejuvenates tired legs.  Improves digestion.  Helps relieve the symptoms of menopause.  Relieves menstrual discomfort when done supported.  Reduces anxiety, fatigue, backache, headache, and insomnia.  Therapeutic for asthma, high blood pressure, osteoporosis, and sinusitis." },
    { id: "yoga_butterfly", name: "Butterfly", nameEs: "Postura de la mariposa", sanskrit: "Baddha Konasana",
      level: "beginner", primary: "adductors", secondary: ["glutes"],
      img: "https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483074/yoga-api/5_i64gif.png",
      desc: "In sitting position, bend both knees and drop the knees to each side, opening the hips.  Bring the soles of the feet together and bring the heels as close to the groin as possible, keeping the knees close to the ground.  The hands may reach down and grasp and maneuver the feet so that the soles are facing upwards and the heels and little toes are connected.  The shoulders should be pulled back and no rounding of the spine.",
      bien: "Opens the hips and groins.  Stretches the shoulders, rib cage and back.  Stimulates the abdominal organs, lungs and heart." },
    { id: "yoga_camel", name: "Camel", nameEs: "Postura del camello", sanskrit: "Ustrasana",
      level: "intermediate", primary: "chest", secondary: ["abdominals", "quadriceps", "shoulders"],
      img: "https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483075/yoga-api/6_ri1w0e.png",
      desc: "From a kneeling position the knees are hip width apart and the thighs are perpendicular to the earth.  The inner thighs are narrowed and rotated slightly inward with the buttocks engaged but not hardened.  The tailbone is tucked under but the hips do not puff forward.  The shins and tops of the feet are pressed firmly into the earth.  The ribcage is open, along with the heart center, but the lower front ribs do not protrude sharply towards the sky.  The lower back lifts the ribs away from the pelvis to keep the lower spine as long as possible.  The base of the palms are pressed firmly against the soles (or heels) of the feet and the fingers are pointed toward the toes.  The arms are extended straight and are turned slightly outward at the shoulder joint so the elbow creases face forward without squeezing the shoulder blades together.  The neck is in a relatively neutral position, neither flexed nor extended, or (for the advanced practitioners only) the head drops back.  Be careful not to strain your neck and harden your throat.  The gaze is either towards the sky or towards the earth, depending upon your flexibility.",
      bien: "Stretches the entire front of the body, the ankles, thighs and groins, abdomen and chest, and throat.  Stretches the deep hip flexors (psoas).  Strengthens back muscles.  Improves posture.  Stimulates the organs of the abdomen and neck." },
    { id: "yoga_cat", name: "Cat", nameEs: "Postura del gato", sanskrit: "Marjaryasana",
      level: "beginner", primary: "lower back", secondary: ["abdominals", "middle back"],
      img: "https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483075/yoga-api/7_a6aspg.png",
      desc: "From box neutral shift some weight to the palms.  The wrists, elbows and shoulders are in one line.  The abdomen is pulled in and up with the spine arched in a strong Cobra spine.  The crown of the head is towards the earth and the neck is relaxed.  The gaze is between the arms towards the belly.",
      bien: "Relieves the spine and neck. Energizes the body." },
    { id: "yoga_chair", name: "Chair", nameEs: "Postura de la silla", sanskrit: "Utkatasana",
      level: "beginner", primary: "quadriceps", secondary: ["glutes", "shoulders"],
      img: "https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483078/yoga-api/9_ewvoun.png",
      desc: "From a standing position, the feet are together and rooted into the earth with toes actively lifted.  The knees are bent and the weight of the body is on the heels of the feet.  The pelvis is tucked in and the ribcage is lifted.  The neck is a natural extension of the spine.  The arms are lifted up toward the sky with the elbows straight and the biceps by the ears.  The hands can be together or separated and facing each other with the fingers spread wide.  The gaze is forward.",
      bien: "Strengthens the ankles, thighs, calves, and spine.  Stretches shoulders and chest.  Stimulates the abdominal organs, diaphragm, and heart.  Reduces flat feet.  Energizes the entire body." },
    { id: "yoga_childs_pose", name: "Child's Pose", nameEs: "Postura del niño", sanskrit: "Balasana",
      level: "beginner", primary: "lower back", secondary: ["glutes", "lats"],
      img: "https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483079/yoga-api/10_wzpo85.png",
      desc: "From a kneeling position, the toes and knees are together with most of the weight of the body resting on the heels of the feet.  The arms are extended back resting alongside the legs.  The forehead rests softly onto the earth.  The gaze is down and inward.",
      bien: "Gently stretches the hips, thighs, and ankles.  Calms the brain and helps relieve stress and fatigue.  Relieves back and neck pain when done with head and torso supported." },
    { id: "yoga_corpse", name: "Corpse", nameEs: "Postura del cadáver", sanskrit: "Sivasana",
      level: "beginner", primary: "", secondary: [],
      img: "https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483078/yoga-api/11_dczyrp.png",
      desc: "The body rests on the earth in a supine position with the arms resting by the side body.  The palms are relaxed and open toward the sky.  The shoulder blades are pulled back, down and rolled under comfortably, resting evenly on the earth.  The legs are extended down and splayed open.  The heels are in and the toes flop out.  The eyes are closed.  Everything is relaxed.  The gaze is inward.",
      bien: "Calms the brain and helps relieve stress and mild depression.  Relaxes the body.  Reduces headache, fatigue, and insomnia.  Helps to lower blood pressure." },
    { id: "yoga_cow", name: "Cow", nameEs: "Postura de la vaca", sanskrit: "Bitilasana",
      level: "beginner", primary: "lower back", secondary: ["abdominals", "neck"],
      img: "https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483077/yoga-api/8_wi10sn.png",
      desc: "From  box neutral the ribcage is lifted with a gentle sway in the low back.  The tailbone lifts up into dog tilt.  The eyes are soft and the gaze is to the sky.",
      bien: "Removes fatigue.  Improves breathing and the circulation of blood to the brain.  Rejuvenates the entire body." },
    { id: "yoga_crescent_lunge", name: "Crescent Lunge", nameEs: "Zancada creciente", sanskrit: "Alanasana",
      level: "beginner", primary: "quadriceps", secondary: ["glutes", "shoulders"],
      img: "https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483080/yoga-api/12_pv4p1z.png",
      desc: "From mountain pose, on the inhalation bring the hands up and interlace the fingers together. Exhale, bend to one side, lengthening the opposite of the rib cage and stretch.",
      bien: "Stretches the rib cage, arms and torso.  Tones the oblique muscles." },
    { id: "yoga_crescent_moon", name: "Crescent Moon", nameEs: "Media luna en alto", sanskrit: "Ashta Chandrasana",
      level: "beginner", primary: "abdominals", secondary: ["lats", "shoulders"],
      img: "https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483095/yoga-api/39_hqj0sa.png",
      desc: "From mountain pose, on the inhalation bring the hands up and interlace the fingers together.  Exhale, bend to one side, lengthening the opposite of the rib cage and stretch.",
      bien: "Stretches the rib cage, arms and torso.  Tones the oblique muscles." },
    { id: "yoga_crow", name: "Crow", nameEs: "Postura del cuervo", sanskrit: "Bakasana",
      level: "expert", primary: "shoulders", secondary: ["triceps", "abdominals", "forearms"],
      img: "https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483083/yoga-api/13_hdjxuz.png",
      desc: "From an inverted position, with the hips up and the head down, the arms are bent in a 90-degree angle with the knees resting on the elbows.  The palms are firmly rooted into the earth with knuckles pressed firmly into the earth for support.  The belly is pulled up and in towards the spine with the ribcage and chin lifted.  The weight of the body shifts slightly forward as the toes lift up and off the earth into the full expression of the pose.  The gaze is down and slightly forward.",
      bien: "Strengthens arms and wrists.  Stretches the upper back.  Strengthens the abdominal muscles.  Opens the groin.  Tones the abdominal organs." },
    { id: "yoga_dolphin", name: "Dolphin", nameEs: "Postura del delfín", sanskrit: "Ardha Pincha Mayurasana",
      level: "intermediate", primary: "shoulders", secondary: ["middle back", "hamstrings"],
      img: "https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483080/yoga-api/14_k9lr9a.png",
      desc: "From Downward-Facing Dog, the forearms are planted onto the earth with the elbows narrow and the palms down in a Sphinx position. The pelvis is tucked. The ribcage lifted. The feet are rooted and the legs are straight with the tailbone in dog tilt. The gaze is down and slightly forward.",
      bien: "Calms the brain and helps relieve stress and mild depression. Energizes the body. Stretches the shoulders, hamstrings, calves, arches, and hands. Strengthens the arms and legs. Helps relieve the symptoms of menopause. Relieves menstrual discomfort when done with the head supported. Helps prevent osteoporosis. Improves digestion. Relieves headache, insomnia, back pain, and fatigue. Therapeutic for high blood pressure, asthma, flat feet, sciatica, and sinusitis. Warms up the ankles and the toes." },
    { id: "yoga_downward_facing_dog", name: "Downward-Facing Dog", nameEs: "Perro boca abajo", sanskrit: "Adho Mukha Svanasana",
      level: "beginner", primary: "hamstrings", secondary: ["shoulders", "calves", "lats"],
      img: "https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483081/yoga-api/15_vkviqn.png",
      desc: "From downward_dog.html the legs are straight with the sits bones tilted up and reaching for the sky.  The feet are flat with the heels firmly rooted.  One palm is flat with the knuckles evenly pressed into the earth.  The other hand reaches under the body and grasps the opposite ankle.  The spine is long and the heart is open toward the sky.  The neck is loose and the crown of the head is relaxed toward the earth.  The gaze is toward the center.",
      bien: "Calms the brain and helps relieve stress and mild depression.  Energizes the body.  Stretches the shoulders, neck, hamstrings, calves, arches, and hands.  Strengthens the arms and legs.  Helps relieve the symptoms of menopause.  Relieves menstrual discomfort when done with the head supported.  Helps prevent osteoporosis.  Improves digestion.  Relieves headache, insomnia, back pain, and fatigue.  Therapeutic for high blood pressure, asthma, flat feet, sciatica, and sinusitis." },
    { id: "yoga_eagle", name: "Eagle", nameEs: "Postura del águila", sanskrit: "Garudasana",
      level: "intermediate", primary: "shoulders", secondary: ["quadriceps", "glutes", "middle back"],
      img: "https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483081/yoga-api/16_g7ueht.png",
      desc: "From a standing position the one thigh is crossed over the other with the toes and/or the ankle hooked behind the lower calf.  The weight of the body is balanced on the standing foot.  The arms are crossed in front of the torso so that one arm is crossed above the other arm.  The top arm is tucked into the elbow crook of the bottom arm.  The hands are hooked around each other as well.  Once hooked, the elbows lift up and the fingers stretch towards the ceiling.  The gaze is soft and forward.",
      bien: "Strengthens and stretches the ankles and calves.  Stretches the thighs, hips, shoulders, and upper back.  Improves concentration.  Improves sense of balance." },
    { id: "yoga_extended_hand_to_toe", name: "Extended Hand to Toe", nameEs: "Mano al pie extendida", sanskrit: "Utthita Hasta Padangusthasana",
      level: "expert", primary: "hamstrings", secondary: ["quadriceps", "abdominals"],
      img: "https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483084/yoga-api/17_l9joyu.png",
      desc: "From mountain.html pose, lift one foot.  Bend forward and catch the toes with the fingers.  Place the other hand on the hip to square the hip towards the front.  Slowly straighten the knee and the torso and open the leg to one side.  Use a strap if necessary.  Gaze towards the front or opposite of the extended leg for balance.",
      bien: "Opens the hips and groins.  Stretches the hamstrings, IT bands and legs.  Improves balance." },
    { id: "yoga_extended_side_angle", name: "Extended Side Angle", nameEs: "Ángulo lateral extendido", sanskrit: "Utthita Parsvakonasana",
      level: "beginner", primary: "adductors", secondary: ["quadriceps", "lats", "abdominals"],
      img: "https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483083/yoga-api/18_aqufak.png",
      desc: "From warrior II the lower body stays static while the upper body is folded forward at the crease of the hip.  One arm is extended toward the front with the bicep by the ear and the fingers spread wide while the other reaches down to the earth on the inside of the thigh.  The upper torso and the gaze twist up towards the sky.",
      bien: "Strengthens and stretches the legs, knees, and ankles.  Stretches the groin, spine, waist, chest, lungs, and shoulders. Stimulates abdominal organs. Increases stamina." },
    { id: "yoga_forearm_stand", name: "Forearm Stand", nameEs: "Parada sobre antebrazos", sanskrit: "Pincha Mayurasana",
      level: "expert", primary: "shoulders", secondary: ["triceps", "abdominals", "middle back"],
      img: "https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483084/yoga-api/19_jadqwc.png",
      desc: "From an inverted position, with the body perpendicular to the earth, the weight of the body is supported on the forearms that are parallel and pressed firmly into the earth.  The palms are flat.  The knuckles are evenly pressed into the earth.  The fingers are spread wide.  Both legs reach up toward the sky in a straight line with the pelvis tucked.  The ribcage is lifted.  The gaze is forward.",
      bien: "Strengthens arms and shoulders.  Improves focus and balance.  Stretches the upper and lower back.  Strengthens the abdominal muscles.  Tones the abdominal area." },
    { id: "yoga_forward_bend_with_shoulder_opener", name: "Forward Bend with Shoulder Opener", nameEs: "Flexión adelante con apertura de hombros", sanskrit: "Uttanasana",
      level: "beginner", primary: "hamstrings", secondary: ["shoulders", "chest"],
      img: "https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483085/yoga-api/20_uogrfq.png",
      desc: "From a standing position, the body is folded over at the crease of the hip with the spine long.  The neck is relaxed and the crown of the head is towards the earth.  The feet are rooted into the earth.  The toes are actively lifted.  The spine is straight.  The ribcage is lifted.  The chest and the thighs are connected.  The sacrum lifts up toward the sky in dog tilt.  The fingers are interlaced behind the body and the palms are together.  The arms and elbows are straight.  The shoulder blades rotate towards each other as the hands move forward (away from the lower back).  The gaze is down and inward.",
      bien: "Calms the brain and helps relieve stress and mild depression.  Stimulates the liver and kidneys.  Stretches the hamstrings, calves, and hips.  Strengthens the thighs and knees.  Improves digestion.  Helps relieve the symptoms of menopause.  Reduces fatigue and anxiety.  Relieves headache and insomnia.  Relieves headache and insomnia.  Opens the shoulders." },
    { id: "yoga_garland_pose", name: "Garland Pose", nameEs: "Postura de la guirnalda", sanskrit: "Malasana",
      level: "beginner", primary: "adductors", secondary: ["quadriceps", "glutes", "lower back"],
      img: "https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483093/yoga-api/37_moh7ii.png",
      desc: "From a squatting position the feet are as close together as possible (keep your heels on the floor if you can; otherwise, support them on a folded mat).  The thighs are slightly wider than the torso.  The torso is leaning gently forward and tucked snugly between the thighs.  The elbows are pressed against the inner knees and the palms are together in Anjali Mudra (Salutation Seal).  The knees resist the elbows to help lengthen the front torso.  The gaze is soft and forward.",
      bien: "Stretches the ankles, groins and back torso.  Tones the belly." },
    { id: "yoga_half_boat", name: "Half Boat", nameEs: "Medio barco", sanskrit: "Ardha Navasana",
      level: "beginner", primary: "abdominals", secondary: ["quadriceps"],
      img: "https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483073/yoga-api/2_ozh7sv.png",
      desc: "From a seated position the hands are gripped around the back of the legs and the knees are bent in a 90 degree angle.  Both legs are pulled in towards the abdomen.  The core is engaged to maintain balance on the sits bones (be sure that the back does not round).  The front of the torso lengthens between the pubis and top of the sternum as the spine extends in both directions reaching up to the sky and rooting down to the earth.  The gaze is forward and Bandhas are engaged.",
      bien: "Strengthens the abdomen, hip flexors and spine.  Stimulates the kidneys, thyroid, prostate glands and intestines.  Helps relieve stress.  Improves digestion." },
    { id: "yoga_half_lord_of_the_fishes", name: "Half Lord of the Fishes", nameEs: "Media torsión espinal", sanskrit: "Ardha Matsyendrasana",
      level: "beginner", primary: "lower back", secondary: ["glutes", "middle back"],
      img: "https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483091/yoga-api/32_hafoa0.png",
      desc: "Begin in a seated position. Bend one knee so the sole of your foot is close to the opposite inner thigh. Bend your opposite knee in, foot on the floor, heel to the outside of your bent thigh. Extend your arm (same side of your Lotus leg) high into the sky and begin to twist it to the outside of your bent knee. Use your opposite hand as leverage to twist deeper. Hook your elbow to the outside of your thigh and gaze over your back shoulder. If you want to extend your twist deeper, wrap your arm around the shin of your bent knee and sweep your opposite arm around to meet it. Catch opposite fingertips or the wrist. Keep a long spine.",
      bien: "Stretches the shoulders, the chest, the thighs, the groins, and the abdomen.  Strengthens the legs and the ankles.  Improves balance." },
    { id: "yoga_half_moon", name: "Half-Moon", nameEs: "Media luna", sanskrit: "Ardha Chandrasana",
      level: "intermediate", primary: "glutes", secondary: ["abdominals", "hamstrings", "adductors"],
      img: "https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483085/yoga-api/21_etedlp.png",
      desc: "From a standing position one leg is straight while the other is extended back parallel to the earth (or a little above parallel) and one hand is on the earth (beyond the little-toe side of the foot, about 12 inches) while the other hand is extended up towards the sky.  The shoulder blades are squeezed together and the fingers move outward in opposing directions.  The weight of the body is supported mostly by the standing leg while the bottom hand has very little weight on it but is used intelligently to regulate balance.  The upper torso is rotated open to the sky.  Both hips are externally rotated.  Energy is extended actively through the flexed toes to keep the raised leg strong.  The inner ankle of the standing foot is lifted strongly upward, as if drawing energy from the earth.  The sacrum and scapulae are firmly pressed against the back torso and lengthen the coccyx toward the raised foot.  The gaze is either up or down, depending on the condition of the neck.  If injured the gaze is down.",
      bien: "Strengthens the abdomen, ankles, thighs, buttocks and spine.  Stretches the groins, hamstrings, calves, shoulders, chest and spine.  Improves coordination and sense of balance.  Helps relieve stress.  Improves digestion." },
    { id: "yoga_handstand", name: "Handstand", nameEs: "El pino", sanskrit: "Adho Mukha Vrksasana",
      level: "expert", primary: "shoulders", secondary: ["triceps", "abdominals", "forearms"],
      img: "https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483085/yoga-api/22_ojzmr8.png",
      desc: "In this inverted posture the weight of the body is on the hands - shoulder-width apart with fingers forward and parallel to each other (if the shoulders are tight, the index fingers are turned out slightly).  The shoulder blades are firm against the back torso and pulled up toward the tailbone.  The upper arms are rotated outward with the eye of the elbow to the front of the room to keep the shoulder blades broad while the outer arms hug inward in opposing forces for balance and stability.  The palms are spread and the bases of the index fingers are pressed firmly against the earth.  Balance is maintained by keeping the Bandhas engaged while pressing the earth away with straight arms and flexed feet.  The gaze is down and forward.",
      bien: "Strengthens the shoulders, arms and wrists.  Stretches the belly.  Improves sense of balance.  Calms the brain and helps relieve stress and mild depression." },
    { id: "yoga_king_pigeon", name: "King Pigeon", nameEs: "Paloma real", sanskrit: "Eka Pada Rajakapotasana",
      level: "expert", primary: "quadriceps", secondary: ["chest", "shoulders", "abdominals"],
      img: "https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483087/yoga-api/25_rssro9.png",
      desc: "From a seated position with the hips squared, one leg is extended forward with the knee bent and parallel to the earth.  The front heel is rooted close to the groin (or extended out in a 90 degree angle if flexibility allows).  The other leg is extended back with the knee bent and perpendicular to the earth.  The back foot is hooked on the inside of the elbow of the back arm.  The front elbow is bent upward perpendicular to the earth with the bicep by the ear.  The fingers are interlaced to connect the bind behind the body and assist in opening the chest.  The gaze is natural and forward.",
      bien: "Stretches the thighs, groins (psoas), abdomen, chest, shoulders and neck.  Stimulates the abdominal organs.  Opens the shoulders and chest." },
    { id: "yoga_lotus", name: "Lotus", nameEs: "Postura del loto", sanskrit: "Padmasana",
      level: "intermediate", primary: "adductors", secondary: ["glutes", "lower back"],
      img: "https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483091/yoga-api/31_ozseum.png",
      desc: "Bring the bottom ankle and place it on top of the opposite knee, both ankles will be resting on top of the thighs.",
      bien: "Opens the hips, groin and stretches the knees, ankles and thighs.  Strengthens the back and calms the mind, reduces stress and anxiety.  Improves circulation and blood flow in the pelvis." },
    { id: "yoga_low_lunge", name: "Low Lunge", nameEs: "Zancada baja", sanskrit: "Anjaneyasana",
      level: "beginner", primary: "quadriceps", secondary: ["glutes", "adductors"],
      img: "https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483086/yoga-api/23_k2jccj.png",
      desc: "The front knee is bent in a 90-degree angle directly above the ankle and the back knee is resting on the earth with the top of the back foot pressed firmly into the earth.  The hips are squared and pressed forward.  The inner thighs scissor towards each other.  The pelvis is tucked under to protect the low back.  The ribcage is lifted.  The arms are lifted.  The hands can be together or separated and facing each other with the fingers spread wide.  The gaze is forward.",
      bien: "Stretches the chest, lungs, neck, belly and groin (psoas).  Strengthens the shoulders, arms and back muscles.  Strengthens and stretches the thighs, calves and ankles." },
    { id: "yoga_pigeon", name: "Pigeon", nameEs: "Postura de la paloma", sanskrit: "Supta Kapotasana",
      level: "intermediate", primary: "glutes", secondary: ["abductors", "adductors"],
      img: "https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483088/yoga-api/24_ulgsjo.png",
      desc: "Lie on the back in supine position.  Bend the knees, heels close to SI bones and cross one ankle over the opposite knee.  Thread the hands or reach through between the thighs.  Lift the foot off the floor and hold the bent knee behind the thigh or shin to bring it closer to the chest, make sure that the acrum is rooted to the floor.",
      bien: "Stretches the hamstrings and quads.  If the elbow is used to push the thigh, it opens the hips as well." },
    { id: "yoga_plank", name: "Plank", nameEs: "Plancha de yoga", sanskrit: "Phalakasana",
      level: "beginner", primary: "abdominals", secondary: ["shoulders", "chest", "triceps"],
      img: "https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483088/yoga-api/26_mxkzlo.png",
      desc: "The body is parallel to the earth.  The weight of the body is supported by straight arms and active toes.  The abdomen is pulled up towards the spine and the pelvis is tucked in.  The neck is a natural extension of the spine and the chin is slightly tucked.  The palms are flat and the elbows are close to the side body.  The joints are stacked with the wrists, elbows and shoulders in a straight line perpendicular to the earth.  The gaze follows the spine and the eyes are focused down.",
      bien: "Strengthens the arms, wrists, and spine.  Tones the abdomen." },
    { id: "yoga_plow", name: "Plow", nameEs: "Postura del arado", sanskrit: "Halasana",
      level: "intermediate", primary: "middle back", secondary: ["hamstrings", "neck", "lats"],
      img: "https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483088/yoga-api/27_m4yux9.png",
      desc: "From a supine position, the upper back rests on the earth with the hips and legs revolved back over the torso above and beyond the head towards the earth.  The torso is perpendicular to the earth.  The legs are fully extended with no bend at the knees as the toes reach for the earth.  The hands are either supporting the lower back or extended behind the back on the earth with extended elbows and fingers interlaced (as flexibility allows), opening the shoulders.  The neck is straight.  The chin tucked.  Do not look to the side as this may injure the neck.  The is gaze inward.",
      bien: "Calms the brain.  Stimulates the abdominal organs and the thyroid glands.  Stretches the shoulders and spine.  Helps relieve the symptoms of menopause.  Reduces stress and fatigue.  Therapeutic for backache, headache, infertility, insomnia,  and sinusitis." },
    { id: "yoga_pyramid", name: "Pyramid", nameEs: "Postura de la pirámide", sanskrit: "Parsvottanasana",
      level: "intermediate", primary: "hamstrings", secondary: ["calves", "lower back"],
      img: "https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483089/yoga-api/28_uu58tt.png",
      desc: "From a standing position with one leg forward and one back lean the torso forward at the crease of the hip joint.  Stop when the torso is parallel to the floor.  Press the fingertips or flat palms to the floor on either side of the front foot, maintaining a straight elongated spine.  If it isn’t possible to touch the floor, or to maintain a straight spine, support the hands on a pair of blocks.  Press the thighs back and lengthen the torso forward, lifting up through the top of the sternum.  Then, as flexibility allows, bring the front torso closer to the top of the thigh without rounding the spine.  Eventually the long front torso will rest down on the thigh.  The gaze is down.",
      bien: "Calms the brain.  Stretches the spine, the shoulders, the hips and the hamstrings.  Strengthens the legs.  Stimulates the abdominal organs.  Improves posture and sense of balance.  Improves digestion." },
    { id: "yoga_reverse_warrior", name: "Reverse Warrior", nameEs: "Guerrero invertido", sanskrit: "Parsva Virabhadrasana",
      level: "beginner", primary: "abdominals", secondary: ["quadriceps", "lats", "adductors"],
      img: "https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483089/yoga-api/29_ww7bot.png",
      desc: "From warrior II , the lower body stays static while the upper body arches back in a gentle back bend.  The top arm is extended back with the bicep by the ear and the fingers spread wide.  The other arm slides down the back leg resting on the thigh or shin, but not the knee joint.  The gaze is up towards the sky.",
      bien: "Strengthens and stretches the legs, knees, and ankles.  Stretches the groin, spine, waist, chest, lungs, and shoulders.  Stimulates abdominal organs.  Increases stamina.  Relieves backaches, especially through second trimester of pregnancy.  Therapeutic for carpal tunnel syndrome, flat feet, infertility, osteoporosis, and sciatica." },
    { id: "yoga_seated_forward_bend", name: "Seated Forward Bend", nameEs: "Flexión sentada adelante", sanskrit: "Paschimottanasana",
      level: "beginner", primary: "hamstrings", secondary: ["lower back", "calves"],
      img: "https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483091/yoga-api/30_gumpl3.png",
      desc: "From a seated position with the sits bones rooted into the earth the legs extend forward to the degree that the chest and thighs can stay connected.  The fingers wrap around the toes.  The upper torso folds forward at the crease of the hips with the spine long.  The gaze is forward.",
      bien: "Calms the brain and helps relieve stress and mild depression.  Stretches the spine, shoulders and hamstrings.  Stimulates the liver, kidneys, ovaries and uterus.  Improves digestion.  Helps relieve the symptoms of menopause and menstrual discomfort.  Soothes headache and anxiety.  Reduces fatigue.  Therapeutic for high blood pressure, infertility, insomnia and sinusitis.  Traditional texts say that Paschimottanasana increases appetite, reduces obesity and cures diseases." },
    { id: "yoga_shoulder_stand", name: "Shoulder Stand", nameEs: "Postura sobre los hombros", sanskrit: "Salamba Sarvangasana",
      level: "intermediate", primary: "neck", secondary: ["middle back", "abdominals"],
      img: "https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483091/yoga-api/33_r7motl.png",
      desc: "From a supine position, the upper back is resting on the earth with the hips straight up towards the sky.  The torso is perpendicular to the earth.  The legs are fully extended and the toes are active.  The hands are either supporting the lower back or extended up by the side body in matchstick.  The neck is flat on the earth and the chin is tucked in.  The gaze is inward.",
      bien: "Calms the brain and helps relieve stress and mild depression.  Stimulates the thyroid and prostate glands and abdominal organs.  Stretches the shoulders and neck.  Tones the legs and buttocks.  Improves digestion.  Helps relieve the symptoms of menopause.  Reduces fatigue and alleviates insomnia.  Therapeutic for asthma, infertility, and sinusitis." },
    { id: "yoga_side_plank", name: "Side Plank", nameEs: "Plancha lateral de yoga", sanskrit: "Vasisthasana",
      level: "intermediate", primary: "abdominals", secondary: ["shoulders", "glutes"],
      img: "https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483093/yoga-api/34_qle5tp.png",
      desc: "From an arm balance position the weight of the body is supported on one side and distributed equally between the bottom arm and foot while the other (top) arm lifts with fingers spread wide and the other (top) foot stacks on top.  The grounded (bottom) foot is flat and gripping the earth from the outside edge of the foot.  If flexibility of the foot is limited then instead of gripping the earth with a flat foot, the weight of the body is balanced on the side edge of the foot that is flexed instead of flat.  The arm supporting the weight of the body and the grounded foot actively press into the floor as the shoulder blades firm against the back and then widen away from the spine drawing toward the tailbone.  Bandhas are engaged to maintain balance and stability.  The crown of the head reaches away from the neck and the gaze is up towards the hand.",
      bien: "Calms the brain and helps relieve stress and mild depression.  Stretches the shoulders, hamstrings, calves, and arches.  Strengthens the arms and legs.  Helps relieve the symptoms of menopause.  Helps prevent osteoporosis.  Improves digestion.  Relieves headache, insomnia, back pain, and fatigue.  Therapeutic for high blood pressure, asthma, flat feet, sciatica." },
    { id: "yoga_side_splits", name: "Side Splits", nameEs: "Espagat lateral", sanskrit: "Upavistha Konasana",
      level: "expert", primary: "adductors", secondary: ["hamstrings"],
      img: "https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483093/yoga-api/40_dkmow6.png",
      desc: "From a wide stance the legs are open and extended sideways to your degree of flexibility.  The outer edges of the feet are rotated and gripping toward the earth.  The weight of the body is supported by the arms.  The palms are rooted into the earth with the fingers pointing towards the body.  There should be no excess weight on the knee or ankle joints as you lower down to your degree of flexibility. The gaze is down and slightly forward.",
      bien: "Stretches the insides and backs of the legs.  Stimulates the abdominal organs.  Strengthens the spine.  Calms the brain.  Releases groin." },
    { id: "yoga_sphinx", name: "Sphinx", nameEs: "Postura de la esfinge", sanskrit: "Salamba Bhujangasana",
      level: "beginner", primary: "lower back", secondary: ["chest", "abdominals"],
      img: "https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483092/yoga-api/35_dytwvz.png",
      desc: "From a prone position with the pelvic bowl is firmly contracted interiorly towards the center line of the body while the pubis is tucked under.  The legs are extended back and the tops of the feet are flat.  The palms are flat and the elbows are on the mat, stacked right below the shoulders.  On an inhalation, lift the sternum and extend the neck away from shoulders with the elbows, palms and pelvic bone firmly attached to the mat.",
      bien: "Strengthens the spine.  Stretches the chest, the lungs, the shoulders and the abdomen.  Stimulates the abdominal organs.  Opens the heart and the lungs." },
    { id: "yoga_splits", name: "Splits", nameEs: "Espagat", sanskrit: "Hanumanasana",
      level: "expert", primary: "hamstrings", secondary: ["quadriceps", "glutes"],
      img: "https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483092/yoga-api/36_a2z20a.png",
      desc: "The hips are parallel and squared to the earth with one leg extended forward.  The opposite leg extended back with the knee and foot squared to the earth.  The inner thighs scissor towards each other.  The hands are by the side body or at the heart center in Anjali Mudra (Salutation Seal) or stretched straight up toward the sky.  The ribcage is lifted.  The heart is open.  The gaze is forward.",
      bien: "Stretches the thighs, hamstrings, and groin.  Stimulates the abdominal organs." },
    { id: "yoga_standing_forward_bend", name: "Standing Forward Bend", nameEs: "Flexión de pie adelante", sanskrit: "Uttanasana",
      level: "beginner", primary: "hamstrings", secondary: ["calves", "lower back"],
      img: "https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483093/yoga-api/38_yb3thk.png",
      desc: "From a standing position, the body is folded over at the crease of the hip with the spine long.  The neck is relaxed and the crown of the head is towards the earth.  The feet are rooted into the earth with the toes actively lifted.  The spine is straight.  The ribcage is lifted.  The chest and the thighs are connected.  The sacrum lifts up toward the sky in dog tilt.  The fingertips are resting on the earth next to the toes.  The gaze is down or slightly forward.",
      bien: "Calms the brain and helps relieve stress and mild depression.  Stimulates the liver and kidneys.  Stretches the hamstrings, calves, and hips.  Strengthens the thighs and knees.  Improves digestion.  Helps relieve the symptoms of menopause.  Reduces fatigue and anxiety.  Relieves headache and insomnia." },
    { id: "yoga_tree", name: "Tree", nameEs: "Postura del árbol", sanskrit: "Vrksasana",
      level: "beginner", primary: "glutes", secondary: ["quadriceps", "calves", "abductors"],
      img: "https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483094/yoga-api/41_veknug.png",
      desc: "From a standing position, one foot is rooted into the earth with the opposite heel rooted into the inner thigh with the toes pointing towards the earth.  The pelvis and the chin are tucked in.  The arms are lifted above the head with the palms together in prayer position.  The gaze is forward.",
      bien: "Strengthens the legs, ankles, and feet.  Improves flexibility in the hips and knees.  Improves balance." },
    { id: "yoga_triangle", name: "Triangle", nameEs: "Postura del triángulo", sanskrit: "Trikonasana",
      level: "beginner", primary: "hamstrings", secondary: ["adductors", "abdominals", "lats"],
      img: "https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483096/yoga-api/42_jawxqw.png",
      desc: "From a standing position, the legs are straight and separated into a wide stance.  The feet are aligned and flat on the earth with the back foot in a 60-degree angle towards the front.  The inner thighs are rotated externally away from each other.  The pelvis is tucked and the ribcage is lifted.  One arm extends up towards the sky as the other reaches down to the earth.  Both arms are aligned with the shoulders in a straight line.  The fingers reach out as the shoulder blades squeeze together.  The gaze is toward the front.",
      bien: "Stretches and strengthens the thighs, knees, and ankles.  Stretches the hips, groin, hamstrings, calves, shoulders, chest, and spine.  Stimulates the abdominal organs.  Helps relieve stress.  Improves digestion.  Helps relieve the symptoms of menopause.  Relieves backache, especially through second trimester of pregnancy.  Therapeutic for anxiety, flat feet, infertility, neck pain, osteoporosis, and sciatica." },
    { id: "yoga_upward_facing_dog", name: "Upward-Facing Dog", nameEs: "Perro boca arriba", sanskrit: "Urdhva Mukha Svanasana",
      level: "beginner", primary: "chest", secondary: ["lower back", "shoulders", "triceps"],
      img: "https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483096/yoga-api/43_m3nxjk.png",
      desc: "The body is in a prone position parallel to the earth.  The weight of the body is supported equally by the straight arms and the tops of the feet which press firmly into the earth.  The shoulders are rotated back and down.  The ribcage is lifted and pulled thru to the front in a slight upper thoracic backbend.  The joints are stacked with the wrists, elbows and shoulders in a straight-line.  The neck is a natural extension of the spine and the chin is slightly tucked.  The abdomen is pulled up towards the spine.  The palms are flat and the elbows are close to the side body.  The gaze is forward.",
      bien: "Improves posture.  Strengthens the spine, arms, and wrists.  Stretches the chest, lungs, shoulders, and abdomen.  Firms the buttocks.  Stimulates abdominal organs.  Helps relieve mild depression, fatigue, and sciatica.  Therapeutic for asthma." },
    { id: "yoga_warrior_one", name: "Warrior One", nameEs: "Guerrero I", sanskrit: "Virabhadrasana One",
      level: "beginner", primary: "quadriceps", secondary: ["glutes", "shoulders", "chest"],
      img: "https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483096/yoga-api/44_dqeayo.png",
      desc: "From a standing position, the legs are in a wide stance with the feet aligned and flat on the earth.  The back foot is in a 60-degree angle towards the front.  The hips are squared.  The inner thighs are rotated towards each other.  The front knee is bent in a 90-degree angle directly above the ankle.  The arms extend up to the sky with the biceps by the ears.  The hands can be together or separated and facing each other with the fingers spread wide.  The ribcage is lifted and the pelvis tucked.  The gaze is forward.",
      bien: "Stretches the chest, lungs, shoulders, neck, belly and groin (psoas).  Strengthens the shoulders, arms and back muscles.  Strengthens and stretches the thighs, calves and ankles." },
    { id: "yoga_warrior_three", name: "Warrior Three", nameEs: "Guerrero III", sanskrit: "Virabhadrasana Three",
      level: "intermediate", primary: "hamstrings", secondary: ["glutes", "lower back", "shoulders"],
      img: "https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483097/yoga-api/46_lz6v7i.png",
      desc: "From a standing position, one leg is rooted and perpendicular to the earth while the other leg is raised, extended back and parallel to the earth.  The head of the thighbone of the standing leg presses back towards the heel and is actively rooted into the earth.  The arms and the extended leg lengthen in opposing directions with Bandhas engaged.  The hips are squared and the tailbone presses firmly into the pelvis.  The arms, torso, and extended raised leg should be positioned relatively parallel to the floor.  The gaze is forward or down.",
      bien: "Strengthens the ankles and legs.  Strengthens the shoulders and muscles of the back.  Tones the abdomen.  Improves balance and posture." },
    { id: "yoga_warrior_two", name: "Warrior Two", nameEs: "Guerrero II", sanskrit: "Virabhadrasana Two",
      level: "beginner", primary: "quadriceps", secondary: ["glutes", "adductors", "shoulders"],
      img: "https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483096/yoga-api/45_ehimr1.png",
      desc: "From a standing position, the legs are separated into a wide stance.  The front knee is bent in a 90-degree angle directly above the ankle.  The back leg is extended and straight with the outside edge of the back foot gripping the earth in a 60-degree angle towards the front.  The inner thighs are externally rotated away from each other.  The pelvis is tucked.  The ribcage is lifted.  The arms are extended out to the sides and are aligned with the shoulders in a straight line with the fingers reaching out as the shoulder blades squeeze together.  The gaze is toward the front fingers.",
      bien: "Strengthens and stretches the legs and ankles.  Stretches the groin, chest, lungs, and shoulders.  Stimulates abdominal organs.  Increases stamina.  Relieves backaches, especially through second trimester of pregnancy.  Therapeutic for carpal tunnel syndrome, flat feet, infertility, osteoporosis, and sciatica." },
    { id: "yoga_wheel", name: "Wheel", nameEs: "Postura de la rueda", sanskrit: "Urdhva Dhanurasana",
      level: "expert", primary: "chest", secondary: ["shoulders", "quadriceps", "lower back"],
      img: "https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483097/yoga-api/47_w2jsof.png",
      desc: "Pressed up from a supine position, lying on your back, the palms are rooted into the earth with the fingers pointed towards the heels.  The feet are grounded.  The hips are pressed up.  The thighs are rotated inward.  The thoracic spine is arched creating a strong crescent arch along the spinal column.  The gaze is forward.",
      bien: "Strengthens the arms, wrists, legs, buttocks, abs, and spine.  Stimulates the thyroid and pituitary.  Increases energy and counteracts depression.  Therapeutic for asthma, back pain, infertility, and osteoporosis." },
    { id: "yoga_wild_thing", name: "Wild Thing", nameEs: "Postura salvaje", sanskrit: "Camatkarasana",
      level: "intermediate", primary: "chest", secondary: ["shoulders", "glutes", "lower back"],
      img: "https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483097/yoga-api/48_unoav6.png",
      desc: "From downward dog pose, elevate one leg toward the sky and stack the corresponding hip over the other hip.  Bring the upper heel as close to the buttocks as possible.  The hips remain stacked; then bring the shoulders forward slowly over the hands.  Replace the corresponding hand to the upraised leg with the other hand and flip yourself over and extend the top hand forward.  The bottom foot is now facing toward the front of the mat and you remain on the ball of the top foot and the corresponding knee is bent.  Continue to lift hips up towards the sky and continue reaching the free hand towards the front of the room and slightly downwards.  Allow the head to curl back.",
      bien: "Stretches the chest, shoulders, back, and throat.  Strengthens and opens the hips, hip flexors, and thighs." }
  ];

  /* Las deja con la misma forma que un ejercicio del catálogo, que es lo que
     permite que entren en los filtros, en las rutinas y en el entrenamiento
     sin tocar nada más. Una sola imagen: no son un movimiento con ida y
     vuelta, son una postura que se sostiene. */
  function crudos() {
    return POSTURAS.map(function (p) {
      return {
        id: p.id,
        name: p.name,
        nameEs: p.nameEs + (p.sanskrit ? ' (' + p.sanskrit + ')' : ''),
        force: 'static',
        level: p.level,
        mechanic: 'compound',
        equipment: 'body only',
        primaryMuscles: p.primary ? [p.primary] : [],
        secondaryMuscles: p.secondary,
        instructions: [p.desc, p.bien ? 'Beneficios: ' + p.bien : ''].filter(Boolean),
        category: 'yoga',
        images: [p.img]
      };
    });
  }

  g.Yoga = { crudos: crudos, cuantas: POSTURAS.length };
})(window);
